apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: arr
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: arr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  namespace: arr
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: arr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 20Gi