---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: democratic-csi-secrets
  namespace: democratic-csi
spec:
  encryptedData:
    TRUENAS_API_KEY: AgATMMlahWM+7fqwiAwZuhlNrdylbG4HoUSYc+Ab9lWfdAFKHZ5WwOEIDmPEHzKDUlMVETu4BDr4tTNlNoB0laEKTk2mbcWH71hIVpVbb6ZYgWDRxuqoSj0B+7K4w6NCqnRmM5G4/rN+nP1xxzEiYTYi6AIVE/FDFzimdYm8aTK+T1SpNW5x+xndJ5K+ZyDTDfduc0XYlFue5mCvpoQt3pFfdK1yughmEzTF6gytEz50bPJRDwMCamArIx/r3xL/lchk+ewmWfrYSJVrHWcvGcP4ntZNVTzRdIWnSb+TglWPbJA1G6XGK4iASwbs7I4SqBu9/pjiNVdhTvgUIZjKtHxbIUUsuvWaI6QTlRAcSzlYFOGX3sA7rlY2lAk3knmUb1Ez6UK+ZqheW8Fsnwr5Ur6gU1we3B+7jNXecFrbyM38UX+NGJuZUK7ZEFAjHidyEkOui8olGlAQ7U61iR8/9jXjl3TiEtRo3YQrzNUrTp4rXChqqvoWGRU6u/9viG79YTUESpfsvRSpcJRJ+iie1gIENYn3gBkAx10azimGK8zXfcVfF/5y1D5TDM9HD1pncf3rvyIpyYhNg8e4WH7k00S0WC8FfxyIXshWDnH1FPFSge5UsnndAm+sOgzZ1cGlWBSYqXG9NLqD0B67SQ9rQFzzfCKVhn/uZwp9Am2eO778SWkDMg/Q80KKdk9x/I+SJT7RJp9OY3vSCIvnvbXwxz6pvdLFxfx/q08oNqfJ8EUr9L91HwSruU9v2hZF9v/h7TLWL392MVaAgF6X0TULAcfs+uA=
  template:
    metadata:
      name: democratic-csi-secrets
      namespace: democratic-csi
    type: Opaque
