---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: form-proxy
spec:
  encryptedData:
    .dockerconfigjson: AgDHhMAZjZ1BhA6jsz8eFvP6ySxmyDqpZuND7Yuwh0BxMyn0+f3JDtN9WOpo6SGHXzqqzr3d6OVhwCv7iPAVVp8DGkl+RjS6LgM+jfY+T6q9gGm0SrwV/azPUnndTGf+p9TpXjaNEoFmCqmGHj55FpsheU3B3Myt7ukHlUXIM4PNOo+DKF/At3PacckW9he+h67qx9FR/BJYlDpV3qUNua68VIrY+trsOj0cfU4H1eimSAlvt1xGyorbTrvXnXXYBTzy6ybQ8jaTa7wPzbl31UEplCe6PsLmgSfRMcE+ZBE5B5guezg0yF7iaq9VJgB8EJltHkwexVU5EjojMbcCRtU/mpeHixwFHZqY15sLtQDY9xWCjB6oZVCJe0FzGulcCWUMrASFG9Qn6awa/LiikKwh5PKltmg/vi4n3lF6UABTaRi788tqO1Ebku9/LBgteyxFVIKZJOrrTwaxyiL/eY5aP60biNGu3RydsDI1SiRfBx8CGtDejF1GERAxk3/dYR14I5wKwSxueFqXGt3kkS6EdFfkjFarv67wHNl2CVzmuNYeWd5AC8AlCNkqGzRDqpbvlpBaBKZcQaqnYJNgMG88cU9oqwRFjgJ+Ie/3WVg4+WG7VRmD/UEFUc652iMmrUv1VbXnD91E8PfA5RJqftyRucxfdeLTkCEPmoDtu2ZCfBS5yUFq1ckPVw06pnoRFmFsd41qHnlFiTpdmLHkQB6QfB8jPsbB8bIp68CfjxJ+J3324Bp2WIkDJKGsRM2p8dqooQJG3onXQUfq3oryFAxTMNIDYwB4BNhpDOkPWAJ0kH774pdrabjuDlxvIXGWTi5tgnGY9cIxfpGKjC9a2DvPzv3yMfqftG/XzFB9w8BiYR6YPo80HAXwcWHgvJal2DTZTiL07vLOrDOy1J43RzvP11Ni2Iz5SMZsvLkBbrzKAeM=
  template:
    metadata:
      labels:
        app.kubernetes.io/component: email
        app.kubernetes.io/name: form-proxy
        app.kubernetes.io/part-of: weblio
      name: ghcr-credentials
      namespace: form-proxy
    type: kubernetes.io/dockerconfigjson
