---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: migration-helper
spec:
  encryptedData:
    .dockerconfigjson: AgACZFd2ARxoGa0hqUrs7KA611WwOM6BMsTZpEcGspUCq7ktpW4ILa49lsUJbeKbH0xu9ocNQr3noqXNC05PDuSaTbct1dhYFBnjQPHwmBFhyKMtiFXqXLdYZsnC8yWA3Qd11WUv+VSm6V2r5TB0AGFGFal7UsiZmQUeKqtU3xKk7/02gkHKv89pfow7hljNd0Ata8uKw7Il6TTdajS1/1BhobWV6y36BCc4PPIbO3FY/PJ/cqPfb0sItg9ZzP1rvE19kk3cnFYgIq84mncq8iXvIlch5IDtSPHL9jdXEjkkE8in0Pu4FGyHCliNqq/igWPzQXeAtAwirq1Vqz7OVlKfok64vFiSvHtEex1pMX5U0n+6i/MQwdt49YZaNBpPAc0FYLPYpzt30L+NSDPAzsBOVRg6z5AfkxTJdbHF8EZIFG8SCf+PZ8GYPbtvjWFp6YVLDh1hLqh2Jl+aHbKA7zwmKrrHybrouLgBqPXRW44JamNWo1HO4QpQR0xRhV2FcnjVjKq0naUW3xPYKDemHqrXpVosaKDpzhBbQwDV2/Mis/n1aYSR4eKY3kRGLv8qzpZw+Q03WpFn/TnDGiHewB/NSsxuyKdKUADTk3V5z96ywMT3iAgk8xb2rQZduT7ATi8jJrWjibw5ntNTyKCGP3l6u3Y2D4rDlQaEg6I8dzGEivX9uEya27LUBYElm4u2kQxhB33+5/+x8A/+8y3jzw2nw8WRLOUFHYt8F0wXirnynzcbiEJlpm+MEyReV6HgoHV3nrH7fczONr15KZh1MrWPrFCu3WMjR3onBvnhPIE0oB4+MNK90ZS9gqbwbz3vwrofdMUo96PXN92QRYFgizJZUgCkhNY8XZKlo1Jt76wRsWeTJePg2REy36KtHGgHMBoIkkzxEf1KaHwLpKGderXL6IEiRcU4/yMUNB98Sv3QjGs=
  template:
    metadata:
      labels:
        app.kubernetes.io/component: migration
        app.kubernetes.io/name: migration-helper
        app.kubernetes.io/part-of: weblio
      name: ghcr-credentials
      namespace: migration-helper
    type: kubernetes.io/dockerconfigjson
