apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jfa-go
  namespace: arr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 2Gi