apiVersion: v1
kind: Service
metadata:
  name: portainer-loadbalancer
  namespace: portainer-web
  labels:
    app.kubernetes.io/name: portainer-web
    app.kubernetes.io/component: container-manager
    app.kubernetes.io/part-of: portainer
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.86.4
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: portainer-web
    app.kubernetes.io/component: container-manager
  ports:
  - name: edge
    port: 8000
    targetPort: edge
---
apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer-web
  labels:
    app.kubernetes.io/name: portainer-web
    app.kubernetes.io/component: container-manager
    app.kubernetes.io/part-of: portainer
spec:
  selector:
    app.kubernetes.io/name: portainer-web
    app.kubernetes.io/component: container-manager
  ports:
    - protocol: TCP
      name: web
      port: 9000
      targetPort: web