---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secrets
  namespace: redis
spec:
  encryptedData:
    REDIS_ADMIN_PASSWORD: AgB0Xtbbf7vrjtpEC2a2eLpqU9RKoYsJvHB0SoFrsqQIra89Srtq31NDtrF/js/XE5HIZaczlH7dPes6ZiwtMU+TzBa7Qcm6a7zUpVgej2d93t6tpc0Vk8DZSrvYZK6/29K4qjQwquMCyCFHJcpbi5ybieMRU5aJpVYyjmr0ZdhzB3GVtGvauFsh9YsWuZuu/R12SjYdJFLZBsIGeidwHHzx7x8fc701yG1rC0yZwiT3RL5RSchQYJFfky8FHSyaLzBuEAEqQtKPhAUmPGn8gfmSzhmh7gio/EG87VFva/52HYR/g+/NKXzY/WSZx8DRvRy4Te+/9VT88X+6kiWrwjw6BsvlVAKgHGuHD7Tf3aeShPOnfZsQzqhnGxyVa0uSY5pdxl2JUFDcagxhJ1Ct+dxG5U0PDEhj/oDiPqQfUHRr/tnk4VF6W5wxMqrwt2T1gdINMmtluaDD7Vy5Mw049aj2rvE830owBArGNWrAR+dNFRBUUf9R5YB1JbHdNSFaAFI5Vs2lDMkmDqfS2x0AuwF2OyUhYvIBcbeN5R7MWpSXx92Q13J+OBV27f9kEBUMa0BLML/qr+3uV1q5g/mhQ2D4z0+yE9pLilJE825VMDMvSr+1Fq0kzQwkq/3vfgJzlfPTf+DylZdKa/jzbgzzDTk4WwKunRDuCiQn/P/M3sRUb9eHEuYAnZJ44TgFFlLdciP3vbB2v5aLHRA0AII=
    users.acl: AgClPWjGGRcCHiwL/G+6QgVtw1UGDyOtMbsnCu8KLBM+1NXBWzrFcfeQGRi0agXBRVKskkpAeDmdggYr86hr+ReiMaTs7VIP3IYtnh0YI/HHMyaNGxv8BP/4ET6JYNdSLfLn+FxFWk9Nt8z7xV/61izcbgvgsxbivrmxVJHcwmywkxLCJW6IfT8fESC1MdTx+xAhkDrKS2Kw5mp7Q+65CHSFUzYtYzGAHkaYcil2qoUI5HpcTtnX7ONlrcCvtbdXumBPI0/wG2psCKFVi/pCb3EQRn17E4PNI9BXWDrKKfAW5alhSl6aCckkCGwcWMCSAOCnOijLSLf4bA4fiKdHjG6Qw0f8WJGdER0jSsvJjRMkIQr4jrTf9oAXo3HTKOIWpjpEvWk/z8c+xR4aDt65XkaBX8S/hWQOf1iliMi5aJRSZd/S1nhKchhdD+dHgEkW8MgDgKxr4RYRf6GfI99uC8ddUxjiw656B2ZI2pqLj8T4lZvbd7kivkgFhx1jO39MhdYaKXSEsjIYkB4Uvb8UiV9XU5RD+beH3Be9OMoUGopCl3EdT9mGmo3ONMKHBmyintA514ZCgL94U0axOy4XPbwNrhuvbC8C+Bw4FDYtxou/1CA+qCoy/2UzO77ATksKpEXP9PoHee1p71YsN5JArMPoK9Ll3L+6bfOd52LAtKz5TD6D/2XL45g3Ue+7D4teqL+ObZyf41Vu/u+IdxGSzEfVlntoCdjJCKOVwUuI146iCj0/LUdxuuiFQoj0kzuljDdr2OEnJO31ZkxB3dYJ7BfODTrSrnPTmiLhVJ3vJshmX0BXB/bma04P7AgQy7IfGzefpUSePB7pObmlVN30cFSeKFB7YpdMiryGR8RkidYWOObblHvzS5VzLTFo+zQUFwcmuEhW4oW3JILGOGyUYejYXTb7vUcVk+OcQdQw0+l0J3i7dt0ULFaxSdLUrbuZn+u5499LNAhPlk+ru/8oBz5fPA==
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/name: redis
      name: redis-secrets
      namespace: redis
    type: Opaque
