---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secrets
  namespace: redis
spec:
  encryptedData:
    REDIS_ADMIN_PASSWORD: AgBpRyRnGezMF28WFqHC0R34bX6S9iX93TZfSBbCULDiVORPWqhgR3InY39bMM4Y8xQ+ZDZyhpgT131bEy2Zip0xLr+HS3ddsM1DDLqMuYUufU8jJ/X+p8wqp5zi/GTdEMwEL30kLwUvlH8/NMeBEjyEOeCRiO7rtm7OvYq+Jy0eMHrTY1Ah5E0PoRpO5eC1DxWRYWcjHdEC9Sq5RQv1Or5z9sMBEcpbxI65suenmnZwB2hSBAGABQOXnHUR7uo2w18qL8n7OrEiNXmlodKHmh9fgZCLPcRcyiobkzz1XZehItQj6muMgvtWFZDcspia8do+MEHP52RE2gcvN7rcA41Q2SGQbuO8yWzYF3+86INYUulTJ8SESdzd2WMcLQWOt3kCDKL+840xtL6W9LgRV0zJVxZ+6xIJtTmThfBO8obUJYymgxPn67kn+VfHF+gA64OOPaG842AL5quupG/OuBVbOUvlt8HU+8iNHROiAl11vB3M4UOJO6E5AF/5HhNXv7t+9fTHeKO+NtyxDXellwxYBr9NmVjgP3X665ZxlpFBaWVSLj6Epk4teDNcg9Nl1w+d5J2LkD1DfBtPMGq/u/k4EbvS/lG0PGo9YFtfTZXxVMCVI7nX+b+SlBuSfLBCdvxy41OS+jVpv7Zio44dSx0VTzElY9PlWSHtnbJeX4kFKpbLAKsCa2ocVBG61FfddJeHEjztBxCFyo0bytQ=
    users.acl: AgC2dW+W44rj92HhV8Rtwajizj2/LaKARwL7trNK3TPnef+TilUjiD3yBeAPaImh5YST+PV6TrEigrguWxhqWiT5uadJrGobVm4h1gQ4FO19/RRp8xpNzeS/oZIMeEqU2LHWL7DgbCmC1btAZoEoLQIQ0DciCGWIbAoADSnOwZzllxokDibvMXmC/DpFBnc/oWd71CjeMcLDZR9pEokywsunc0QVbIF0kS9QvhqQj91V1xpTMAhDdZPM/GxQio3sm4yRphXDFKOtprNzggoOaS6rKvt9gYqehoUoRxzCV8CotFXA5KwiP0Ssl/YrzZCGBj/K+/xOnknVo94WbPVlyNtfR6BcB+nymGyTItgndQrmSFvwKltpK9flRn4KOkhviWTvgFisWE2XD/oDTq0N6L+3g/JgqbPbIiPzhTEQGlaas1lVTRr2W0AvoJ8jJSojheTqbL5ykFNP5td5ZYG7RLM9tQlY9lWBNOqd2XbKiZ1bBeLxjkRtLdj4YTqS6usaeNE0iImttxQ0qMQunhlEDgAFHJX8nSxNgMnNQY43J96XtKHIM1XZunmJb4TJJ2DYrUcKpXeT5jyEfnKnZlB0M3+65V5BlY2KGrOfKcPWIa+sbHfRPocpmbkU9QhcTY7JqpP+w7iXMOGu41VP7UIIQjIMkReHwEbyICOzdefXRL1RvJdoGte7RFkm8SH6kxJnN2ygMP3OEoOjBcPiATL0amnrNmLG5PwI0npPUUMqeMPpY0bjLCuokNrQBmN6kvzqjJD5IuYHnluYh7CR5V5M/ShcdT9C3kjLqSG8NryJSl6uLcyqJbkNN/FrBAEa2gwS31kDmJ4AvYzZwIdAQJafHHBvyEOJjjf7Qv+GqrrDuonQ91WPUAqX6gCqwZsYdb7vZStn3jYxdFHaSVFn/wX4xuqenjbQCVB3tidXO46Uvk/gv15rHjgI1iHoM8OVNzPMZK07j1A1KZk2Sku4Ow==
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/name: redis
      name: redis-secrets
      namespace: redis
    type: Opaque
