---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secrets
  namespace: redis
spec:
  encryptedData:
    REDIS_ADMIN_PASSWORD: AgAnFQ96/v3XCKnQnMn5fvjlSpLw5wrrB4Fck806n76tVnzthA0tJH07jnUZJqJ8XRvNoxprFK64TCmf3/uIc2fE6x0sg4F5k8Rnp/nE9GevESCmFpYPLpTgewxaJ4HLtgYzHNTRivsZlrs2Prw5lb2mXMnrJcmOhSBVWDNBIdKMXsZ++4b/nOwbtFoXhwvbm6h+zfuSPZmPDWDswlt+Hz45gQvc+8UyPhG+yMItYnsiy5ik6i0EAPdYio+EHbITStmLH2v4U4yqfT70T1PyyEVHF62Hps0VEanGVBjm8RmBYYX9oY7yTiKeuVjxoHHqdAZ/zHIFD+HdSSk8u0tMQ5E+H6Wjgwl6FN5S2iJvVecIpp54WOrtnxAiu/m4IVAo8QGw6Z6PPoLCFL1YlyNOFGMikjXWNIdwGgERMaQiZ+clzoxEPonlRlGTzmd+HV2koSEW4XAu5YEStvwLvJZjxrFfiXhDTrabMYyJ1TwIU95vDkKJQLGFvFD1ygKBaVZkxquXXL6BBEWKrzukMVWTKVpxL2UnnP9OCIXYX3S6ApKLIe+01ssEHqnKgsGKhKI8g7oSWaok/DUBIgXM+eUOqlIdubzapz+UBA0nAttkgRNTQT2X7zCYYJ2lekhbeaZm+SpZPKxOo8UnjkBL99cIVDCZJ5+OO4fXYIDpBegTIXf94JfLIEfQWnq9MSaQnD91gi1PqTyB5y3IxzuzfAA=
    users.acl: AgAdCFviXUJTwKFNx02uYNTdZYd2lLkYRvU5U10MXNxLREQd/z7a7WcqI/aabeZVg5jXbmrTF2RHEHo8Su5ZTlmora66HThRT6Xnaduw5BcrkXn2/IRn5xmGB1VbAB5gBF23VNxTTNR5lt6wh/Coy5CPnSOM/bIsr5DDk4GQLvpn6fS7/SA8uQ/gV/mV9mJLAbkSgKggErukV1KuEIaQaPNHWAuZX+yUbHgIHxzqXisMEsOXYqkvrFZemYW6ncLmx16+DcTBn74QaHDlxRrR6cV4MytAtKnssc588q515F1lqFvnRROaqw3UqKQX9UurV2vPkBLtUl+bWASc0HLdsim/WyohoPBikjXi8LQf+mAA2vsi6ov5HJlklpU4XBz0PC7e367DdFVn4CQ3McMrUe7TrpxJklOvmGrUx/CUkcAXCJgXM+8pXVOSTnzz+hHd+LZFGHVps9onkWX62l9v+2iUMHp9hc/Rx+18O6spe2YHIK3IIC7ywcZIwWJt+iKPIUIeQKbfTU2lE0etpkvgPLR3Wkb6IL6vOrc1lEX5bKY3H/6ZjR3iuFlzvC4WavlkBJRb/HV3nPWiELDl3EQrixGUlV6iDuQr70AVIamFY1kxF5iZ2bLlcfHUkIJElNl+j0304xRvlRJwzkAhESb887WhLm2WHunV/SAxicKE564l6mj2LlcaGtlUzxW50nHg0OvXm35c1ch3RO7eI8Hhlj73b3czdGSv5vG6DdA3VdGxmlQCClxnnv98ThIMhavLfwIBEjJipnaXUl/CZI99F3sbS2YngeZXoCccJ6pSuRj5C9vesXlgWxCikY3RXirDJ7Ed2eOazdORV4LzrK8vyHrhQMz9zUxeb7ob/t3kF2kvLfWfBODiLWLM7iY5nInuiZ4FaTwdlstfmG6IUMFDL4Nf88pYV34gL8IOsZZhBCYM1GHyDyBERtIM8w7GHE/P11CTMAHDh1e3OlBIgwp+6MPDQo+37w==
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/name: redis
      name: redis-secrets
      namespace: redis
    type: Opaque
