apiVersion: v1
kind: Service
metadata:
  name: mega-bridge
  namespace: mega-bridge
  labels:
    app.kubernetes.io/name: mega-bridge
    app.kubernetes.io/component: download
spec:
  selector:
    app.kubernetes.io/name: mega-bridge
    app.kubernetes.io/component: download
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
