apiVersion: v1
kind: Service
metadata:
  name: gotenberg
  namespace: paperless-ngx
  labels:
    app.kubernetes.io/name: gotenberg
    app.kubernetes.io/component: document-management
spec:
  selector:
    app.kubernetes.io/name: gotenberg
    app.kubernetes.io/component: document-management
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000