apiVersion: v1
kind: Service
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: document-management
spec:
  selector:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: document-management
  ports:
    - protocol: TCP
      port: 8000
      targetPort: web