apiVersion: v1
kind: Service
metadata:
  name: tika
  namespace: paperless-ngx
  labels:
    app.kubernetes.io/name: tika
    app.kubernetes.io/component: document-management
spec:
  selector:
    app.kubernetes.io/name: tika
    app.kubernetes.io/component: document-management
  ports:
    - protocol: TCP
      port: 9998
      targetPort: 9998