apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/part-of: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.albinmedoc.se`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-grafana
          port: 80
