---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-secrets
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAMSiDQsxjWut/Rs2H1BnKX+qvhumRSKCM8UX4TcAD/7RTKpOHb1ivM/QUnUTdmKo+IciZ667Vfx/5+CmtZ73r7ABK5Tjh4kMkOvkUt0sI6Ln/gMj+lLgW0amZaPK2+48Xw1a8XbwFp1bkIt+BVS3QRpkIYFu0aUCkXm837mzkbiZhOi8qNUdugozpWXX3enfiV46MpI//YgdyfSqdXNLPFVAupPbOAA+23gj26OBCeYy6Pi8KycXU0t12LD3a1l5IwXPwe3beM08eyKpDJd19BiOmFTBW8cJFSONTiD0zJjC9V8lxahxwu04Gt4v6xIPHSojLniZkG1mun29xv11hgD5luNb+rq1lx2LjgB5+Q4m9oyZlIPnSuoZ+kVx+3mFeUWuxGxyLYqpUv6knUtQkBsoDPOQEMDs3vjn9zpnDLf4ouiGkFM5Rdg1MIGxbbs8EbIwpLB/ND218a7B2kHAGxATYu7aMuRDaTd1Gz8MVwigN8IqCrr/QIi2YZb0g855t+611ZQzYrsvBIcTUqDbkQzEIx6FVGHw2aHLN2KSjhfrH0eU9EDjpxbwaiKvxHdlH179rh3wvdsM7ts+T3Z8DsI8KzUX47mq2TkPbh1J/lBIMQea8RaCfJWy5307xoW4gMqlsTqtzhAxXDjYXq1Hl45qse70TnrRLFDZXM5/ByCGCFaTKQFD2elVb1DLue1B1kYBR88ke+Rg1DO1RyEOxqxQ==
    client_secret: AgCCSxqFcsPELkVPppUTDVdaRN+IBKlS0YajVP1UNYPUgT/mT2zv+adTpmoq/oYKRVHMykKDoAtNmujj+ncHI0QxLWAMGUYz2Gl6pRMx7k06JGIlnuj14uAWgQdOlzFP9EmcHSlcJGqRta0s9qmG8TQF8UG4dWeZ8QZrsWXNI0MD1jJ+KSt+o/jm9qMEFyG1ZzsgyEPSNKk/38DjVvvNrBAs7SNK7wkrJNeMrL1AisO/Mm/CvisHRNMVEqgT3beCuEYnYuQzDArrOrGk76b9NxpmrO7TnAmSMJ7ElPZeW8ERgfHxkGJNVtTJRm/aFLze0Y/CNR3j5InTMoe27gAnFhdnNhb6Hx/iYBe6Pr8LewDVlKpCBtsRocCVVzGSZ4xf9aDA3YmMMlk82mF/TxKJGO/7IhTNMLkAyXtZNrG+99O42g+EzAgwHgi+7nAk7DDhujht8u2r8/9n9zruksUv65LkegKsDx6PnGUjfdt5qtFN12/AqAea/tTbkp2eVBpI6evbnaehJunof6zLP/4QiKfb1ZffBEqRZyJa+FMVeHRUwtz5dZCG4X2J5sfntfLkdtV1X7R/TLwxhg+HMu+8Vdtlc/WEVAHU3snCvUdf7F+KYlC20r57Iy3fvmB16sOCNd8Hw+cy86F2zFootaH/k6rj/Sbg+owb5zMhUQQovNzbDjK/KJ1KHqjN8h+y28Y4H/CDmp+ZIq90EUa9m0FME+CepSNI1HUJQ+CdeUrJN1XXaWHDwt25NpqycnVylSopZBnU2InrQrXopAYHgzmJCSc=
  template:
    metadata:
      name: tailscale-secrets
      namespace: tailscale
    type: Opaque
