apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr
  namespace: arr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 10Gi