apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wishlist
  namespace: wishlist
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 5Gi