apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/albinmedoc/kubernetes
    path: democratic-csi
    targetRevision: HEAD
    helm:
      releaseName: truenas-iscsi
  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/name: democratic-csi
        app.kubernetes.io/component: csi-driver
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
