apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/albinmedoc/kubernetes
    path: tailscale
    targetRevision: HEAD
    helm:
      releaseName: tailscale-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/name: tailscale
        app.kubernetes.io/component: networking
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
