---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plex-media-server-exporter-secrets
  namespace: plex-media-server-exporter
spec:
  encryptedData:
    PLEX_TOKEN: AgAZpsEvE/TRZZzHz2QlYM0xtT8YyxNkbscXYFqBfyhQVXOOlEmSfhgw9t2tZY818jE9/6yag0RjR+uQmFdqyUrPu8UtgGTM+uqH+VZU61cnejwSbirsgoAwgnyyo7B9BjMay7vH0Wxyo+bRes5DbWPmgSzKjiEcN+e18eMU45VsogTDESzfCUtn9pg8RnIdqlhtlyUSCr/Mz8zRVYm95YzlbZh8FqVsEmzKhkds3dnNSUsBofSoSuqmfSVF8C5OkbZeFQMJPdEoL+FgYdAd0CWN5dqC7VVsCnHly/6mLjCayQWmq4N6rFkKGKXhms/jnkoyEdB24yK0BUArnJiSIlDH9vwi03gDIsh8LgwdPg6/3eu6uxWfeydyoPG+yOfSQ4VJ2Rw571L2N1ug/9dsQBXyUxbyPJrYmjY2Z9Yi5CeLYTM30vouVGKvfa8UkmZ1ln+Jf8wmH4TYSNtNOX74XTqCsMytKycTRHKsg0l2SNcSsxBTxlRDU7yJGtbzptJtsy/xMaGjKgDA/SvR+BOjLgohtq3JmgCUgP/PWz+VZ4nzkGG4ytQwUJlDI6lwAURrtkOFHX2VdiECBLMVpw56vG115t4fFQIR3Q2GbWtkcu2pggn6iHcWZ6OYxcjt7LcKxhp+/gX6PfvSl97GPOJEgNasXB8BF4xP5Wowei57FHjfrzbPcwI+j7tYu5v7JMb/kYMWuu4YmAZAuSwz4ggeCwKulxk49A==
  template:
    metadata:
      name: plex-media-server-exporter-secrets
      namespace: plex-media-server-exporter
    type: Opaque
