apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: plex-media-server-exporter
  namespace: plex-media-server-exporter
  labels:
    app.kubernetes.io/name: plex-media-server-exporter
    app.kubernetes.io/component: metrics-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: plex-media-server-exporter
      app.kubernetes.io/component: metrics-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
