apiVersion: v1
kind: Service
metadata:
  name: plex-media-server-exporter
  namespace: plex-media-server-exporter
  labels:
    app.kubernetes.io/name: plex-media-server-exporter
    app.kubernetes.io/component: metrics-exporter
spec:
  selector:
    app.kubernetes.io/name: plex-media-server-exporter
    app.kubernetes.io/component: metrics-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 9594
      targetPort: metrics
