apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbdav
  namespace: arr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 1Gi