apiVersion: v1
kind: Service
metadata:
  name: pve-exporter
  namespace: pve-exporter
  labels:
    app.kubernetes.io/name: pve-exporter
    app.kubernetes.io/component: metrics-exporter
spec:
  selector:
    app.kubernetes.io/name: pve-exporter
    app.kubernetes.io/component: metrics-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 9221
      targetPort: metrics
