---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: democratic-csi-secrets
  namespace: democratic-csi
spec:
  encryptedData:
    TRUENAS_API_KEY: AgAqipUDWZzaKXVgHPxBrTfu5zcN81K35VW3fbAynv97sB+7k1Cld5RoC/Xm3EC14uFAe+qvbwL6Y8lBa+RvivHH8q7+U/6rnYwIQ/qbN23XWefXy61+4wyH6ZVaRkWSxmRuC8S8GVBdXXxGHE584i99Lccrkd1HFHlnC42bbmBfKp+Agw1bst6P2c4hxDhwEPbZ/TbzkJIQMdN6Mv9lUYxYfPJTR0HhqnMXEY6b9nsnscRy9dU95a/to6XHYaSEMBT/4xpG+t9NUUtJSCsrigKK0Zifij404ekkz1A1+uJ0BLJ5l39ZIMztgSQNvpqQpVhxUMfFprrzcI+dZpt9brDaWFhNoKQsVOLZcVjl5t7qfwOCUB3LX7uV+n/onNXFBg5JJEeKNOPuSaWb+Xnv0Kxmn3YYV2o7rnV2Oe0sZyXZGW/lQeO8iSjphyUMe66ZYFhyhYz0TNAMOHzoOnlJgAnMLzErcIevDVBNQ52i8Y2UKgYGJdZz5WjCrmHYwLoIcqWvKwV802igpnjvnLbYPzuuxdJJjNrKyzax0IFEtYyB0CoexPpgJ/GGAIoo/XeTjB1f++ete1deTKGwLqhLeIHiYRu2N7/kWxhFw+0xEmy9dfer0udh5jscSxOJgc28QgrwmDH5rcmplVH+BEiblF+UGM494BIwEM3rwy0+sDI1Gc4gUja1m3QUZUgQPNtpqSYEuiT7x9pk9VjOxlja4DQBW8cNgJ4uwezjwGFrBvxm6BqlZxI2KyUVIf3kDX+E/ruH4SMCGOPO7CrsDiyXGtTNJsw=
  template:
    metadata:
      name: democratic-csi-secrets
      namespace: democratic-csi
    type: Opaque
