apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich
  namespace: immich-minnen
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: minnen
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 100Gi