---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgAiPof+34X8gkdLxg5voEDLTmQL64mp3GAXaJ/KLca8tt082N1lTasq0UMiioAtzjbRLibmpZEkqgqNv/usO8KPOfQ3OsNWrgua8iMsHmlfBsbnGagNR6t1l4SmK6q38IqpdR73DT83EzR2iOe4VFuBGlkDf2HN4YyfdwQosvbJ5yUeQg+h4IUENi3dvp489UKSRHcrPLgwEAVec5fTTT5jtQm2bhy99fIQ9FDlSl6KLb4pproCQM+euNlplc1wSAR4xhyfPBSMuqWVv9F5h2N2HJqfGjBUEGfo0M75JrlFuGqDd5kmtT3ZqkOzQACsSf5WgTnDzbwR5kBmBqA5UTQ7JXQOrWkTO3C5W5fruRM5+96ElMhbDHOMZPYu2qdNL2KOYljzRRvMI2DSHnHEKV9Z1GcUQD3fFiV8r8OPsmAlNbzFYMOXxUdgbH3XGnm8nUforqJjHtt7s6iAnxA7EL85HMk2WNKdi9XdBDvU3LyiIPvtKPt+fpUBIDcTdczw2xgfuqlKM8N0WtZ5lgX7kknMRDsSwgoCI9xhLaM5RTuFO+Up6uNf5vcdjg9yG8LIYnrD0FMGovCqBXe8O4GR369oaSs1iwWL2yf8+SzNgMG/7KK7xF0cnbsdZo6FoCzMNJS/MZ4DRd8lLzbBIMWZ3OsJUTTPkRhzGDNEf1QZ+EeMwBTrKQr+O3XQZqcAdLWUE9Xq9FqSknum3cWDyKZOW4sKYe0NIYpeYFta6GMhx6VCU79y6/E/yr9ysOcfZl9QIfTl44EmyaREvujJ2BrQ7P/sglOzzTwrRbMah2/g8gsL5Ouba73qWEWS9fITeur4ikCdAlk3Mx1B2sLPBF0=
  template:
    metadata:
      name: velero-cloud-credentials
      namespace: velero
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-repo-credentials
  namespace: velero
spec:
  encryptedData:
    repository-password: AgCUuF/VUfQl8x+9DIcIW8uFSJfhTDIP/UjINCTiZGnFzB791NJ+SIA2R0y1yjx0uThiuBZTIOsWZpElB+HhJMrtufMh4+L11DMqzuhnpzKWvcqocIGB/a6/0ZSR8F7T8W5+wY6NU+pny0WQLN7iq2xCWGJ8DTFhLeXvWkvyONpXZjDYD/dDV8QcZC33RUKmutLZuDEzgcSMHQ2AFoxlaN6cRnyX0KgxWK6DD7V2a7fVDekW7AR5JgNNCwNcVAKN0MvcpOrUyT6LllA4H17OUnTAxYQzecQyQ1yJOJs0D+Pyx9ZjZ1rdDPHRypEM6zghx0qP9U7CY0o47g0OdxTivY+vXsNo9BujU3SXGtdBP+i4dXuv+Ddmj2caIBQNyuRYtKlIlIVDOF0Ww7zMlEm6vOYLy+uubcJJvgkhWr77hzGKMED4w+ja9FMpFvVJOyI7KBEIDmXTgE5Ekoy3Yo1BzVuv1PQGdP6G9FMQlkxkMAKDvBOYya7C5MxMUYS4h2gCus/l++VFOF8fs8lCeU+kWnd8VWEcJ8KPxZ+rSY4lQION5Fic3Xq4UC4wh7y/XN6sPsnW8vE5yga3cJLnmNwqyZu6XB1JJ8zWABwTRCH23wJBuw7qgpM//l9LDm0d2CW9f3g4ZeY4uhbbWWnZcAmRTKVz5CPYVL+lZKD5yzet38cBZQFAAxYc/D7JNiGEEoiaU81z5S3yY08E8+VD8rgiNT2Dr3SGfw==
  template:
    metadata:
      name: velero-repo-credentials
      namespace: velero
    type: Opaque
